modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="mse_tjcmod"
version="1.0.0"
displayName="TheJoCraft's Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="christian, MCreator"

[[dependencies.mse_tjcmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



